"""Requerimientos funcionales RF-01 a RF-27 (Formato 06) y extensiones posteriores al baseline.

Nombres canónicos: catálogo oficial (docs/v1.1/uml/use-cases.md, encargo F27B §2). Contenido de las fichas:
comportamiento SOFTWARE IMPLEMENTADO v1.1, tomado de docs/final-report/04-requerimientos.md §4.2,
docs/assumptions.md (A-01 a A-36), los Form Requests de app/Http/Requests y
docs/final-report/traceability-master.md. La prioridad es una priorización analítica del equipo:
Alta = camino principal del proceso; Media = notificación derivada de otra acción.
"""

PRIORIZACION = 'priorización analítica del equipo'

# Alias históricos: rótulos del F9 (v1.0 y v1.1) y del cap. 4 de v1.0 que difieren del nombre canónico.
ALIAS = {
    'RF-03': ('Registrar aprobación o rechazo', 'Registrar aprobación o rechazo'),
    'RF-04': ('Notificar rechazo', 'Notificar rechazo'),
    'RF-05': (None, 'Registrar perfil y criterios'),
    'RF-08': ('Gestionar cuenta y acceso', None),
    'RF-09': ('Gestionar perfil y CV', 'Gestionar perfil y CV'),
    'RF-11': ('Confirmar postulación', 'Confirmar postulación'),
    'RF-14': ('Gestionar cambio de etapa', 'Gestionar cambio de etapa'),
    'RF-15': ('Notificar cambio de etapa', 'Notificar cambio de etapa'),
    'RF-17': ('Generar convocatoria', None),
    'RF-19': ('Registrar entrevista y resultado', 'Registrar entrevista y resultado'),
    'RF-22': ('Presentar comparación', None),
    'RF-23': ('Registrar decisión final humana', None),
    'RF-24': ('Registrar selección', None),
    'RF-26': ('Notificar resultado y cierre', 'Notificar resultado y cierre'),
}

# id, nombre, descripción, actor, entradas, salidas, prioridad, pre, flujo, alternativos, post, TO-BE, evidencia
RF = [
    ('RF-01', 'Registrar requerimiento de personal',
     'El sistema debe permitir al área solicitante registrar un requerimiento de personal.',
     'Área solicitante',
     'Puesto requerido, área, número de plazas (1–50), tipo de contrato, justificación (20–2000 caracteres) y fecha requerida (opcional, desde hoy).',
     'Requerimiento en estado «borrador», con historial y registro de auditoría.', 'Alta',
     'Usuario autenticado con rol de área solicitante de la organización.',
     ['Abre el formulario de nuevo requerimiento.', 'Ingresa los datos del puesto y la justificación.',
      'El sistema valida los datos.', 'El sistema guarda el requerimiento en borrador con la organización del usuario y registra el historial.'],
     ['a) Datos inválidos: el sistema muestra los errores por campo y no guarda.',
      'b) Usuario sin el rol: el acceso se deniega.'],
     'Requerimiento en borrador, visible solo para el área. RR. HH. y Dirección no ven borradores (A-05).',
     ['TB-01'], 'JobRequestWorkflowTest (test_rf01_*), E2E-02, E2E-13'),
    ('RF-02', 'Validar y corregir requerimiento',
     'El sistema debe permitir enviar el requerimiento a RR. HH., que lo valida u observa, y al área corregir y reenviar lo observado.',
     'Área solicitante (enviar, corregir y reenviar) · RR. HH. (validar u observar)',
     'Acción: enviar, validar u observar. La observación lleva un comentario de 5 a 1000 caracteres. Datos corregidos.',
     'Estado «enviado», «observado» o «validado», con historial.', 'Alta',
     'Enviar: requerimiento propio en borrador u observado. Validar u observar: requerimiento enviado de la organización.',
     ['El área envía el requerimiento (estado «enviado»).', 'RR. HH. lo revisa.', 'RR. HH. lo valida (estado «validado»).'],
     ['a) RR. HH. lo observa con un comentario (estado «observado»); el área corrige y reenvía; vuelve al paso 2.',
      'b) Observación sin comentario: se rechaza la acción.',
      'c) Transición no permitida: el sistema la rechaza.'],
     'Requerimiento validado, disponible para la decisión del Aprobador / Dirección.',
     ['TB-02', 'TB-03', 'TB-04'], 'JobRequestWorkflowTest (test_rf02_*), E2E-02, E2E-13'),
    ('RF-03', 'Registrar aprobación o rechazo del requerimiento',
     'El sistema debe permitir al Aprobador / Dirección aprobar o rechazar un requerimiento validado, con motivo obligatorio si lo rechaza.',
     'Aprobador / Dirección',
     'Decisión (aprobar o rechazar) y motivo (obligatorio al rechazar, hasta 1000 caracteres).',
     'Estado final «aprobado» o «rechazado», con historial y auditoría.', 'Alta',
     'Requerimiento «validado» de la misma organización.',
     ['Revisa el requerimiento validado.', 'Elige aprobar o rechazar.', 'El sistema registra la decisión y el historial.'],
     ['a) Rechazo sin motivo: el sistema lo impide.',
      'b) Usuario de otra organización o sin el rol: acceso denegado.',
      'c) Requerimiento no validado: la acción no está disponible.'],
     'Aprobado: habilita crear la vacante (RF-05). Rechazado: dispara RF-04.',
     ['TB-05'], 'JobRequestWorkflowTest (test_rf03_*), CrossTenantAccessTest, E2E-03, E2E-13'),
    ('RF-04', 'Notificar rechazo del requerimiento',
     'El sistema debe notificar automáticamente al área solicitante el rechazo de su requerimiento, con el motivo.',
     'Sistema (destinatario: área solicitante)',
     'Rechazo registrado en RF-03, con su motivo.',
     'Notificación en la plataforma y por correo, que se registra con el driver «log»: sin envío real (OUT-08).', 'Media',
     'Rechazo registrado (RF-03).',
     ['Al registrarse el rechazo, el sistema genera la notificación.', 'El solicitante la ve en sus notificaciones y en el detalle del requerimiento.'],
     ['a) Si el requerimiento se aprueba, no hay notificación de rechazo.'],
     'El área solicitante queda informada del rechazo y de su motivo.',
     ['TB-06'], 'JobRequestWorkflowTest (test_rf04_*); E2E-03 (rechazo sin motivo impedido)'),
    ('RF-05', 'Registrar perfil y criterios del puesto',
     'El sistema debe permitir a RR. HH. crear una vacante desde un requerimiento aprobado y registrar su perfil y sus criterios ponderados.',
     'RR. HH.',
     'Requerimiento aprobado; título, resumen, lugar, tipo de contrato y plazas; perfil (formación, experiencia, funciones y competencias); criterios con etapa, ponderación y rango.',
     'Vacante en estado «borrador» con perfil y criterios.', 'Alta',
     'Requerimiento «aprobado» de la misma organización.',
     ['Crea la vacante desde el requerimiento aprobado.', 'Completa el perfil del puesto.',
      'Define los criterios. Se proponen tres editables (40/30/30, A-09).', 'El sistema guarda la vacante en borrador.'],
     ['a) Requerimiento no aprobado: no se puede crear la vacante.', 'b) Datos inválidos: errores por campo.',
      'c) Vacante no «borrador»: el perfil y los criterios ya no se editan (A-07).'],
     'Vacante en borrador, lista para configurar.',
     ['TB-07'], 'VacancyPublicationTest (test_rf05_*), E2E-04, E2E-13'),
    ('RF-06', 'Configurar y validar vacante',
     'El sistema debe permitir configurar la convocatoria y mostrar una lista de validación previa a la publicación.',
     'RR. HH. (configura) · Sistema (valida)',
     'Plazas (sin superar las aprobadas), fechas de apertura y cierre y plazo objetivo del proceso (opcional, v1.1).',
     'Lista de validación: ponderaciones, rangos, fechas, criterios y plazas.', 'Alta',
     'Vacante en borrador de la organización.',
     ['Configura la convocatoria.', 'El sistema evalúa la lista de validación.', 'El sistema muestra qué está completo y qué falta.'],
     ['a) Configuración inválida: se puede guardar en borrador, pero no publicar (A-06).',
      'b) Más plazas que las aprobadas: error (A-08).'],
     'Vacante lista para publicar cuando todas las validaciones se cumplen.',
     ['TB-08', 'TB-09'], 'VacancyPublicationTest (test_rf05_rf06_*, test_rf06_*), E2E-04'),
    ('RF-07', 'Publicar vacante',
     'El sistema debe publicar en el portal público de empleos las vacantes que cumplan la validación.',
     'RR. HH.',
     'Orden de publicación de una vacante en borrador.',
     'Vacante «publicada», visible en el portal público de empleos.', 'Alta',
     'Vacante en borrador con la validación completa.',
     ['RR. HH. solicita publicar.', 'El sistema vuelve a validar la configuración.', 'El sistema cambia el estado y la muestra en el portal.'],
     ['a) Validación incumplida: no se publica y se indica el motivo.', 'b) Otro rol: no puede publicar (solo RR. HH.).'],
     'Los postulantes pueden consultar la vacante y postular.',
     ['TB-10'], 'VacancyPublicationTest (test_rf07_*), E2E-04, E2E-13'),
    ('RF-08', 'Gestionar cuenta y acceso del postulante',
     'El sistema debe permitir al postulante crear su cuenta e iniciar sesión.',
     'Postulante',
     'Nombre, correo y contraseña para el registro; credenciales para el inicio de sesión.',
     'Cuenta global con rol de postulante, sin organización (A-04), y sesión iniciada.', 'Alta',
     'Visitante sin sesión (registro) o postulante registrado (inicio de sesión).',
     ['Se registra con sus datos.', 'El sistema crea la cuenta con rol de postulante.', 'Inicia sesión.'],
     ['a) Correo ya registrado o datos inválidos: errores.', 'b) Credenciales incorrectas: acceso denegado.',
      'c) Más de 5 intentos por minuto: bloqueo temporal.'],
     'Postulante autenticado. No se exige verificación de correo (A-01).',
     ['TB-11'], 'CandidateRegistrationTest, AuthenticationTest, E2E-01, E2E-05'),
    ('RF-09', 'Gestionar perfil y CV del postulante',
     'El sistema debe permitir al postulante completar su perfil y cargar su CV en PDF de forma privada.',
     'Postulante',
     'Teléfono, ciudad, nivel educativo, título u ocupación, años de experiencia y resumen (opcional); CV en PDF de hasta 5 MB.',
     'Perfil completo y CV guardado en disco privado con nombre UUID.', 'Alta',
     'Postulante autenticado.',
     ['Completa el perfil.', 'Carga el CV.', 'El sistema valida y guarda el perfil y el CV.'],
     ['a) CV que no es PDF o supera 5 MB: se rechaza.', 'b) Campos obligatorios faltantes: errores.'],
     'Postulante habilitado para postular. No se piden DNI ni fecha de nacimiento (A-15).',
     ['TB-12'], 'CandidateProfileTest (test_rf09_*), E2E-05, E2E-13'),
    ('RF-10', 'Registrar postulación',
     'El sistema debe registrar una única postulación por postulante y vacante publicada y vigente.',
     'Postulante',
     'Vacante elegida.',
     'Postulación en estado «postulado», con la referencia al CV vigente.', 'Alta',
     'Vacante publicada y no cerrada; perfil completo y CV cargado (A-11); sin postulación previa a esa vacante.',
     ['Elige una vacante publicada.', 'Confirma la postulación.', 'El sistema valida los requisitos y la registra.'],
     ['a) Postulación duplicada: se rechaza (A-10).', 'b) Perfil incompleto o sin CV: se rechaza con indicaciones.',
      'c) Vacante cerrada: se rechaza (E2E-12).'],
     'Postulación registrada; dispara RF-11.',
     ['TB-13'], 'ApplyToVacancyTest (test_rf10_*), VacancyClosureTest, E2E-05, E2E-12, E2E-13'),
    ('RF-11', 'Confirmar postulación al postulante',
     'El sistema debe confirmar cada postulación con un código de seguimiento y un aviso de recepción.',
     'Sistema (destinatario: postulante)',
     'Postulación registrada.',
     'Código de seguimiento y notificación de recepción.', 'Media',
     'Postulación registrada (RF-10).',
     ['El sistema genera el código de seguimiento.', 'Envía la notificación de recepción.', 'El postulante la ve en sus postulaciones.'],
     ['a) No hay caminos alternativos: toda postulación registrada se confirma.'],
     'El postulante tiene constancia de su postulación.',
     ['TB-14'], 'ApplyToVacancyTest (test_rf10_rf11_*), E2E-05'),
    ('RF-12', 'Consultar y revisar postulaciones',
     'El sistema debe listar las postulaciones de cada vacante y mostrar el expediente con datos, CV e historial.',
     'RR. HH. (también consulta el Aprobador / Dirección)',
     'Vacante y postulación seleccionadas.',
     'Listado por vacante; expediente con datos, CV (descarga autorizada) e historial.', 'Alta',
     'Vacante de la organización del usuario.',
     ['Abre la vacante.', 'Revisa el listado de postulaciones.', 'Abre el expediente y, si lo necesita, descarga el CV.'],
     ['a) Vacante o postulación de otra organización: no es accesible.', 'b) El CV solo se descarga si la Policy lo autoriza.'],
     'Solo consulta: no cambia datos.',
     ['TB-15'], 'ApplicationReviewTest (test_rf12_*), E2E-06'),
    ('RF-13', 'Registrar preselección o descarte',
     'El sistema debe permitir a RR. HH. preseleccionar o descartar una postulación. El descarte lleva un motivo interno.',
     'RR. HH.',
     'Acción (preseleccionar o descartar) y motivo interno obligatorio al descartar (5–1000 caracteres).',
     'Estado «preseleccionado» o «descartado», con historial; notificación RF-15.', 'Alta',
     'Transición permitida por la máquina de estados (A-13); vacante sin decisión final registrada (A-28).',
     ['Revisa el expediente.', 'Preselecciona o descarta.', 'El sistema registra la etapa y el historial y notifica.'],
     ['a) Descarte sin motivo: error.', 'b) Decisión final ya registrada: acción bloqueada.', 'c) Transición no permitida: error.'],
     'Postulación en su nueva etapa; el postulante recibe el aviso (RF-15), sin el motivo interno.',
     ['TB-16'], 'ApplicationReviewTest (test_rf13_*), SelectionRegistrationTest, E2E-06'),
    ('RF-14', 'Gestionar cambio de etapa de la postulación',
     'El sistema debe permitir a RR. HH. cambiar la etapa de una postulación según las transiciones permitidas, con historial.',
     'RR. HH.',
     'Etapa de destino entre las asignables manualmente y observación opcional (hasta 1000 caracteres).',
     'Nueva etapa, con historial y notificación RF-15.', 'Alta',
     'Transición válida (A-13); vacante no cerrada; sin decisión final (A-28).',
     ['Elige la etapa de destino.', 'El sistema valida la transición.', 'Registra la etapa y el historial y notifica.'],
     ['a) «Seleccionado» y «no seleccionado» no se asignan a mano: solo por RF-24 y RF-25.',
      'b) Transición no permitida o posterior a la decisión: error.',
      'c) Al programar una sesión, la etapa avanza sola a «en evaluación» o «en entrevista» (A-16).'],
     'Postulación en la etapa elegida, con trazabilidad del cambio.',
     ['TB-23'], 'ApplicationReviewTest (test_rf14_*), ApplicationStatusTest, E2E-06, E2E-13'),
    ('RF-15', 'Notificar cambio de etapa al candidato',
     'El sistema debe avisar al postulante de cada cambio de etapa, sin revelar observaciones internas.',
     'Sistema (destinatario: postulante)',
     'Cambio de etapa (RF-13 o RF-14).',
     'Aviso de cambio de etapa sin observaciones internas (A-14).', 'Media',
     'Cambio de etapa registrado.',
     ['El sistema genera el aviso.', 'El postulante lo ve en sus notificaciones y en el detalle de la postulación.'],
     ['a) Si el cambio se debe a la programación de una sesión, se envía la convocatoria (RF-17) en lugar de este aviso (A-16).'],
     'El postulante conoce su etapa.',
     ['TB-17'], 'ApplicationReviewTest (test_rf13_rf15_*), E2E-06'),
    ('RF-16', 'Programar evaluación',
     'El sistema debe permitir a RR. HH. programar una evaluación con un evaluador de la organización.',
     'RR. HH.',
     'Tipo de evaluación, evaluador de la organización, modalidad, lugar o enlace, fecha y hora futuras, duración opcional (15–480 min) e indicaciones.',
     'Evaluación programada; postulación en «en evaluación»; convocatoria RF-17.', 'Alta',
     'Postulación en «preseleccionado» o «en evaluación»; la vacante tiene criterios de la etapa y no está cerrada (A-16).',
     ['Elige la postulación.', 'Completa los datos de la sesión.', 'El sistema valida, programa y envía la convocatoria.'],
     ['a) Evaluador de otra organización o sin el rol: error (A-17).', 'b) Fecha pasada: error (A-18).',
      'c) Etapa no permitida: error.', 'd) No hay cancelación ni reprogramación (A-22).'],
     'Sesión programada y comunicada.',
     ['TB-18'], 'EvaluationTest (test_rf16_*), E2E-13'),
    ('RF-17', 'Generar convocatoria de evaluación',
     'El sistema debe generar la convocatoria al postulante y el aviso de asignación al evaluador.',
     'Sistema (destinatarios: postulante y evaluador)',
     'Sesión programada (RF-16 o RF-18).',
     'Convocatoria con fecha, modalidad, lugar e indicaciones; aviso al evaluador.', 'Media',
     'Sesión programada.',
     ['El sistema genera la convocatoria.', 'La envía al postulante y avisa al evaluador asignado.'],
     ['a) El postulante nunca ve puntajes, observaciones ni el resultado de la entrevista (A-21).'],
     'Postulante y evaluador informados de la sesión.',
     ['TB-19'], 'EvaluationTest (test_rf16_rf17_*), InterviewTest (test_rf18_*), E2E-13'),
    ('RF-18', 'Programar entrevista',
     'El sistema debe permitir a RR. HH. programar una entrevista con un evaluador asignado y su convocatoria.',
     'RR. HH.',
     'Evaluador, modalidad, lugar, fecha futura, duración opcional e indicaciones.',
     'Entrevista programada; postulación en «en entrevista»; convocatoria RF-17.', 'Alta',
     'Postulación en «preseleccionado», «en evaluación» o «en entrevista»; vacante no cerrada (A-16).',
     ['Elige la postulación.', 'Completa los datos de la entrevista.', 'El sistema valida, programa y envía la convocatoria.'],
     ['a) Evaluador no válido o fecha pasada: error.', 'b) Etapa no permitida: error.'],
     'Entrevista programada y comunicada.',
     ['TB-20'], 'InterviewTest (test_rf18_*), VacancyClosureTest, E2E-13'),
    ('RF-19', 'Registrar entrevista y su resultado',
     'El sistema debe permitir al evaluador asignado registrar, una sola vez, los puntajes, el resultado y las observaciones de su sesión.',
     'Evaluador asignado',
     'Puntaje de cada criterio de la etapa (con comentario opcional). En la entrevista, además, el resultado (recomendado, recomendado con reservas o no recomendado) y observaciones (10–2000 caracteres); en la evaluación las observaciones son opcionales.',
     'Sesión «realizada» con resultados que no se pueden editar.', 'Alta',
     'Ser el evaluador asignado; resultados aún no registrados; vacante no cerrada (A-19).',
     ['Abre la sesión asignada.', 'Registra los puntajes, el resultado y las observaciones.', 'El sistema valida (RF-20) y guarda.'],
     ['a) Puntaje fuera de rango o criterio faltante: error (RF-20).', 'b) Otro evaluador: acceso denegado.',
      'c) Resultados ya registrados o vacante cerrada: bloqueado.'],
     'Resultados disponibles para el ranking (RF-21).',
     ['TB-21'], 'InterviewTest (test_rf19_*), EvaluationTest, E2E-07, E2E-13'),
    ('RF-20', 'Validar rangos y ponderaciones',
     'El sistema debe validar que las ponderaciones y los rangos de los criterios sean coherentes y que cada puntaje esté dentro de su rango.',
     'Sistema (lo configura RR. HH.)',
     'Ponderaciones y rangos de los criterios; puntajes registrados.',
     'Aceptación o rechazo, con mensaje.', 'Alta',
     'Configuración de la vacante, registro de puntajes o cálculo del ranking.',
     ['Al configurar o publicar: la suma de ponderaciones es la configurada (100 por defecto, A-06), los pesos son positivos y el mínimo es menor que el máximo.',
      'Al registrar resultados: cada puntaje está en su rango y se cubren todos los criterios de la etapa.',
      'Al calcular el ranking: la configuración es válida.'],
     ['a) Configuración inválida: la vacante no se publica y el ranking se rechaza.', 'b) Puntaje fuera de rango: no se registra.'],
     'Solo se usan datos coherentes para evaluar y comparar.',
     ['TB-09', 'TB-22'], 'WeightingValidatorTest, ScoreSheetValidatorTest, RankingServiceTest (test_rf20_*), E2E-04, E2E-07'),
    ('RF-21', 'Calcular ranking configurable',
     'El sistema debe calcular un ranking ponderado, determinista y explicable, sin seleccionar a ningún candidato.',
     'Sistema',
     'Resultados de sesiones «realizada» de la vacante y de su organización, y ponderaciones.',
     'Ranking de 0 a 100 con aportes por criterio, empates marcados (1, 2, 2, 4) y candidatos incompletos aparte. **No cambia estados.**', 'Alta',
     'Vacante con configuración válida.',
     ['Filtra las postulaciones no descartadas de la vacante (A-23).', 'Promedia los puntajes por criterio y normaliza con la fórmula de A-24.',
      'Ordena y marca los empates, sin desempatarlos (A-26).'],
     ['a) Configuración inválida: error.', 'b) Candidato sin todos los puntajes: se lista aparte, sin imputar cero (A-25).'],
     'Ranking disponible como apoyo. Ninguna postulación cambia de estado.',
     ['TB-24'], 'RankingServiceTest (test_rf21_*), RankingComparisonTest, E2E-08, E2E-13'),
    ('RF-22', 'Presentar comparación de candidatos',
     'El sistema debe presentar la comparación de candidatos con criterios, promedios, aportes, total y posición.',
     'RR. HH. · Aprobador / Dirección',
     'Vacante de la organización.',
     'Vista de comparación explicable.', 'Alta',
     'Permiso para ver el ranking de la vacante (Policy de rol y organización).',
     ['Abre la comparación de la vacante.', 'El sistema calcula el ranking (RF-21) y lo presenta con sus aportes.'],
     ['a) Otra organización o rol no autorizado: acceso denegado.'],
     'Información disponible para la decisión humana (RF-23).',
     ['TB-25'], 'RankingComparisonTest (test_rf21_rf22_*, test_rf22_*), E2E-08'),
    ('RF-23', 'Registrar decisión final de selección',
     'El sistema debe permitir al Aprobador / Dirección registrar la decisión final humana, con confirmación explícita y justificación.',
     'Aprobador / Dirección',
     'Candidato elegido (finalista con resultados completos), justificación (20–2000 caracteres) y confirmación explícita de decisión humana.',
     'Decisión única e inmutable, con la posición y el puntaje del elegido en ese momento, y auditoría. **No cambia estados.**', 'Alta',
     'Rol de Aprobador de la misma organización; vacante sin decisión previa; candidato finalista con resultados completos.',
     ['Consulta la comparación (RF-22).', 'Elige a un finalista, que puede no ser el primero del ranking.', 'Escribe la justificación y confirma que la decisión es suya.',
      'El sistema registra la decisión.'],
     ['a) Sin confirmación o con justificación corta: error.', 'b) Candidato no finalista o incompleto: error.',
      'c) Ya existe una decisión: bloqueado.', 'd) Otro rol, incluido RR. HH.: acceso denegado.'],
     'Habilita RF-24 y bloquea los cambios manuales de etapa (A-28). **El sistema nunca decide por sí mismo.**',
     ['TB-26'], 'FinalDecisionTest (test_rf23_*), RankingComparisonTest::test_rf23_calculating_the_ranking_never_selects_a_candidate, E2E-09, E2E-12, E2E-13'),
    ('RF-24', 'Registrar selección del candidato',
     'El sistema debe permitir a RR. HH. aplicar la decisión final registrando la selección del candidato decidido.',
     'RR. HH.',
     'Orden de registrar la selección.',
     'La postulación decidida pasa a «seleccionado». Solo puede haber una por vacante (índice único).', 'Alta',
     'Decisión final registrada (RF-23); vacante no cerrada.',
     ['Abre la vacante con decisión.', 'Registra la selección.', 'El sistema cambia el estado de la postulación decidida.'],
     ['a) Sin decisión final: error de regla de negocio.', 'b) Vacante cerrada: bloqueado.'],
     'Selección registrada; habilita el cierre (RF-25).',
     ['TB-27'], 'SelectionRegistrationTest (test_rf24_*), E2E-10, E2E-12, E2E-13'),
    ('RF-25', 'Cerrar vacante o convocatoria',
     'El sistema debe permitir a RR. HH. cerrar la convocatoria después de registrar la selección.',
     'RR. HH.',
     'Notas de cierre (opcional, hasta 1000 caracteres).',
     'Vacante «cerrada»; las demás postulaciones activas pasan a «no seleccionado»; notificaciones RF-26.', 'Alta',
     'Selección registrada (RF-24).',
     ['Solicita el cierre.', 'El sistema cierra la vacante y actualiza las postulaciones activas.', 'Notifica los resultados (RF-26).'],
     ['a) Sin selección: no se puede cerrar. El cierre sin selección está fuera de la línea base (A-30); en el TO-BE es la propuesta futura TB-F1.',
      'b) Vacante ya cerrada: error, sin notificar de nuevo (A-32).'],
     'Convocatoria cerrada. Se bloquean postulaciones, cambios, programación, resultados, decisión y selección.',
     ['TB-28'], 'VacancyClosureTest (test_rf25_*), ApplicationStatusTest, E2E-10, E2E-12, E2E-13'),
    ('RF-26', 'Notificar resultado y cierre al postulante',
     'El sistema debe notificar a cada postulante su propio resultado al cerrar la convocatoria.',
     'Sistema (destinatarios: postulantes)',
     'Cierre de la vacante (RF-25).',
     'Resultado propio para el seleccionado y para cada no seleccionado, sin puntajes, ranking, justificaciones ni datos de otros.', 'Media',
     'Vacante cerrada.',
     ['El sistema identifica a los destinatarios.', 'Envía a cada uno su resultado.'],
     ['a) Las postulaciones descartadas no reciben un segundo aviso (A-31).', 'b) Un reintento del cierre falla antes de notificar (A-32).'],
     'Cada postulante conoce su resultado.',
     ['TB-29'], 'ProcessResultNotificationTest (test_rf26_*), E2E-10, E2E-13'),
    ('RF-27', 'Generar registro de auditoría',
     'El sistema debe registrar de forma de solo inserción las acciones críticas y permitir al Aprobador / Dirección consultarlas.',
     'Sistema (registro) · Aprobador / Dirección (consulta)',
     'Acción crítica ejecutada: usuario, organización, acción, entidad, fecha y metadatos permitidos.',
     'Registro inmutable y vista de consulta paginada, filtrada por organización.', 'Alta',
     'Registro: se ejecuta una acción crítica. Consulta: rol de Aprobador de la organización.',
     ['El sistema registra la acción crítica sin datos sensibles.', 'El Aprobador consulta la auditoría de su organización.'],
     ['a) Cualquier UPDATE o DELETE sobre la tabla lo rechaza el trigger de la base.', 'b) Los datos sensibles se descartan (DEF-08).',
      'c) RR. HH. y los demás roles no consultan la auditoría (A-33).'],
     'Trazabilidad de las acciones críticas.',
     ['TB-30'], 'AuditTrailTest (test_rf27_*), AuditLogViewTest, AuditLoggerTest, E2E-11, E2E-13'),
]

EXTENSIONES = [
    ('RF-28', 'Panel operativo descriptivo (candidato)', 'CANDIDATO — NO IMPLEMENTADO',
     'Panel agregado de etapas, tiempos, backlog y cuellos de botella de las convocatorias, sin datos de personas. '
     'Atendería la parte de indicadores de gestión de P5. No tiene rutas, pruebas ni pantallas. El estado '
     '`descriptive_only` de la tarjeta de RF-29 **no** es este panel.',
     'docs/v1.1/scope-preliminary.md; docs/v1.1/uml/use-cases.md (UC-RF28 «propuesto v1.1», sin asociaciones)'),
    ('RF-29', 'Consultar riesgo operacional del proceso (experimental)', 'EXPERIMENTAL — process-only, no productivo',
     'Estima el riesgo de demora del **proceso** de una vacante con un servicio externo opcional (desactivado por '
     'defecto con `ML_SERVICE_ENABLED=false`). **No evalúa candidatos, no decide, no selecciona ni descarta, no '
     'modifica el ranking** y no guarda su resultado. Validado solo con datos sintéticos; no autorizado para producción. '
     'No cambia RF-23.',
     'docs/v1.1/phase-16-laravel-ml-integration.md; docs/v1.1/phase-17-ml-validation.md; UC-RF29 «experimental»'),
]
